### ISSUE TITLE
Fails to open WADL documents

### ISSUE THREAD

**Issue by howels** [blackwinter/wadl#8]
Gem errors out with "ArgumentError: Missing required attribute "id" in element: <wadl:method name='GET'>" when opening http://pubs.vmware.com/vra-62/topic/com.vmware.vra.restapi.doc/identity/api/docs/application.wadl or similar docs from VMware. The document uses wadl="http://wadl.dev.java.net/2009/02", can support be added for this newer version?

**Comment by blackwinter** [comment]
Thanks for the report. According to the spec (since version 20060802), the `id` attribute is "required for globally defined methods, not allowed on locally embedded methods", so I made it optional.

I've released a [prerelease gem](https://rubygems.org/gems/wadl/versions/0.3.1.pre1). Could you check that it works for your use case?

**Comment by howels** [comment]
Thanks very much for fixing, that's loading now.
